# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bayes_mvr_ridge_scaled_X_rcpp <- function(b, S0, S, S1, SplusS0_chol, S_chol) {
    .Call('_mr_mash_alpha_bayes_mvr_ridge_scaled_X_rcpp', PACKAGE = 'mr.mash.alpha', b, S0, S, S1, SplusS0_chol, S_chol)
}

bayes_mvr_ridge_centered_X_rcpp <- function(V, b, S, S0, xtx, V_chol, S_chol, U0, d, Q) {
    .Call('_mr_mash_alpha_bayes_mvr_ridge_centered_X_rcpp', PACKAGE = 'mr.mash.alpha', V, b, S, S0, xtx, V_chol, S_chol, U0, d, Q)
}

dmvnorm_rcpp <- function(x, mu, S) {
    .Call('_mr_mash_alpha_dmvnorm_rcpp', PACKAGE = 'mr.mash.alpha', x, mu, S)
}

inner_loop_general_rcpp <- function(X, Rbar, mu1, V, Vinv, w0, S0, precomp_quants_list, standardize, compute_ELBO, update_V) {
    .Call('_mr_mash_alpha_inner_loop_general_rcpp', PACKAGE = 'mr.mash.alpha', X, Rbar, mu1, V, Vinv, w0, S0, precomp_quants_list, standardize, compute_ELBO, update_V)
}

