# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnorm_rcpp <- function(x, mu, S) {
    .Call('_mr_mash_alpha_dmvnorm_rcpp', PACKAGE = 'mr.mash.alpha', x, mu, S)
}

